/**
 * Dialog template definitions for DialogManager.
 */

const templates = {
  // --- Template Definitions (코드 그룹, 코드, 공통 필드) ---
  codeGroupCreate: {
    dialogLayout: "2-column-grid",
    type: "modal",
    title: "코드그룹 신규 등록",
    fields: [
      {
        id: "id",
        label: "코드그룹 ID",
        type: "text",
        required: true,
        colSpan: 2,
        placeholder: "플레이스홀더",
      },
      {
        id: "name",
        label: "코드그룹 이름",
        type: "text",
        required: true,
        colSpan: 2,
        placeholder: "",
      },
      {
        id: "description",
        label: "코드그룹 설명",
        type: "textarea",
        required: true,
        colSpan: 2,
        placeholder: "",
      },
      {
        id: "usage",
        label: "사용 여부",
        type: "radio-group",
        options: [
          { value: "1", label: "사용", checked: true },
          { value: "0", label: "미사용" },
        ],
      },
    ],
    footerActions: [
      { text: "취소", class: "secondary", size: "medium", action: "close" },
      { text: "등록", class: "primary", size: "medium", action: "submit" },
    ],
  },
  codeGroupDetail: {
    title: "코드그룹 상세",
    fields: [
      {
        id: "id",
        label: "코드그룹 ID",
        type: "text",
        required: true,
        readonly: true,
        placeholder: "",
      },
      {
        id: "name",
        label: "코드그룹 이름",
        type: "text",
        required: true,
        readonly: true,
        placeholder: "",
      },
      {
        id: "description",
        label: "코드 설명",
        type: "textarea",
        layout: "horizontal",
        required: true,
        readonly: true,
        placeholder: "",
      },
      {
        id: "parent",
        label: "상위 코드그룹",
        type: "text",
        readonly: true,
        placeholder: "",
      },
      {
        id: "usage",
        label: "사용 여부",
        type: "radio-group",
        readonly: true,
        options: [
          { value: "1", label: "사용", checked: true },
          { value: "0", label: "미사용" },
        ],
      },
    ],
    footerActions: [
      { text: "닫기", class: "secondary", action: "close" },
      { text: "수정", class: "primary", type: "submit" },
    ],
  },
  codeGroupUpdate: {
    title: "코드그룹 수정",
    fields: [
      {
        id: "id",
        label: "코드그룹 ID",
        type: "text",
        required: true,
        readonly: true,
        placeholder: "",
      },
      {
        id: "name",
        label: "코드그룹 이름",
        type: "text",
        required: true,
        readonly: false,
        placeholder: "",
      },
      {
        id: "description",
        label: "코드그룹 설명",
        type: "textarea",
        required: true,
        readonly: false,
        placeholder: "",
      },
      { id: "parent", label: "상위 코드그룹", type: "text", readonly: false },
      {
        id: "usage",
        label: "사용 여부",
        type: "radio-group",
        readonly: false,
        options: [
          { value: "1", label: "사용", checked: true },
          { value: "0", label: "미사용" },
        ],
      },
    ],
    footerActions: [
      { text: "취소", class: "secondary", action: "cancel" },
      { text: "수정", class: "primary", type: "submit" },
    ],
  },
  codeCreate: {
    title: "코드 신규 등록",
    fields: [
      { id: "group_id", label: "코드그룹 ID", type: "text", required: true, readonly: true },
      {
        id: "group_name",
        label: "코드그룹 이름",
        type: "text",
        required: true,
        readonly: true,
      },
      { id: "id", label: "코드 ID", type: "text", required: true },
      { id: "name", label: "코드 이름", type: "text", required: true },
      { id: "description", label: "코드 설명", type: "textarea", required: true },
      { id: "parent", label: "상위 코드", type: "text" },
      {
        id: "usage",
        label: "사용 여부",
        type: "radio-group",
        options: [
          { value: "1", label: "사용", checked: true },
          { value: "0", label: "미사용" },
        ],
      },
    ],
    footerActions: [
      { text: "취소", class: "secondary", size: "medium", action: "cancel" },
      { text: "등록", class: "primary", type: "submit", size: "medium", action: "submit" },
    ],
  },
  codeDetail: {
    title: "코드 상세",
    fields: [
      {
        id: "group_id",
        label: "코드그룹 ID",
        type: "text",
        required: true,
        readonly: true,
        placeholder: "",
      },
      {
        id: "group_name",
        label: "코드그룹 이름",
        type: "text",
        required: true,
        readonly: true,
        placeholder: "",
      },
      {
        id: "id",
        label: "코드 ID",
        type: "text",
        required: true,
        readonly: true,
        placeholder: "",
      },
      {
        id: "name",
        label: "코드 이름",
        type: "text",
        required: true,
        readonly: true,
        placeholder: "",
      },
      {
        id: "description",
        label: "코드 설명",
        type: "textarea",
        required: true,
        readonly: true,
        placeholder: "",
      },
      { id: "parent", label: "상위 코드", type: "text", readonly: true, placeholder: "" },
      {
        id: "usage",
        label: "사용 여부",
        type: "radio-group",
        readonly: true,
        options: [
          { value: "1", label: "사용", checked: true },
          { value: "0", label: "미사용" },
        ],
      },
    ],
    footerActions: [
      { text: "취소", class: "secondary", size: "medium", action: "cancel" },
      { text: "수정", class: "primary", type: "submit", size: "medium", action: "submit" },
    ],
  },
  codeUpdate: {
    title: "코드 수정",
    fields: [
      {
        id: "group_id",
        label: "코드그룹 ID",
        type: "text",
        required: true,
        readonly: true,
        placeholder: "",
      },
      {
        id: "group_name",
        label: "코드그룹 이름",
        type: "text",
        required: true,
        readonly: true,
        placeholder: "",
      },
      {
        id: "id",
        label: "코드 ID",
        type: "text",
        required: true,
        readonly: true,
        placeholder: "",
      },
      {
        id: "name",
        label: "코드 이름",
        type: "text",
        required: true,
        readonly: false,
        placeholder: "",
      },
      {
        id: "description",
        label: "코드 설명",
        type: "textarea",
        required: false,
        readonly: false,
        placeholder: "",
      },
      { id: "parent", label: "상위 코드", type: "text", readonly: false, placeholder: "" },
      {
        id: "usage",
        label: "사용 여부",
        type: "radio-group",
        readonly: false,
        options: [
          { value: "1", label: "사용", checked: true },
          { value: "0", label: "미사용" },
        ],
      },
    ],
    footerActions: [
      { text: "취소", class: "secondary", size: "medium", action: "cancel" },
      { text: "저장", class: "primary", type: "submit", size: "medium", action: "submit" },
    ],
  },
  commonField: {
    width: "600px",
    dialogLayout: "mixed-flex",
    title: "개발중-필드모음",
    fields: [
      {
        id: "validation_text",
        label: "커스텀 유효성 검사 (Text)",
        type: "text",
        placeholder: "'test' 라고 입력해야 통과",
        flexStyle: { flex: "1 1 100%" },
        validate: (value, formData) => {
          if (value === 'test') {
            return true;
          } else {
            return "'test' 라고 입력해주세요!";
          }
        },
      },
      {
        id: "text_vertical",
        label: "텍스트 (세로)",
        type: "text",
        layout: "vertical",
        required: true,
        flexStyle: { flex: "1 1 calc(50% - 8px)"},
        placeholder: "텍스트 입력",
        value: "기본 텍스트 (가로)",
        "data-custom": "my-data",
      },
      {
        id: "text_default",
        label: "텍스트(가로기본)",
        type: "text",
        required: true,
        placeholder: "텍스트 입력",
        flexStyle: { flex: "1 1 calc(50% - 8px)" },
        value: "기본 텍스트 (세로)",
        "data-custom": "my-data",
      },
      {
        id: "memo",
        label: "텍스트에어리어",
        type: "textarea",
        required: true,
        placeholder: "여러 줄 입력",
        flexStyle: { flex: "1 1 100%" },
        value: "기본\n텍스트 에어리어",
        rows: 5,
      },
      {
        id: "select",
        label: "선택 필드 (가로)",
        type: "select",
        layout: "horizontal",
        required: true,
        flexStyle: { flex: "1 1 100%" },
        value: "opt2",
        options: [
          { value: "", text: "선택하세요" },
          { value: "opt1", text: "옵션 1" },
          { value: "opt2", text: "옵션 2" },
          { value: "opt3", text: "옵션 3", disabled: true },
        ],
      },
      {
        id: 'expire',
        label: '만료일 (날짜)',
        type: 'date',
        required: true,
        flexStyle: { flex: "1 1 calc(50% - 8px)" },
      },
      { id: 'birth', label: '출생 연도 (연도)', type: 'date', granularity: 'year', placeholder: 'YYYY', flexStyle: { flex: "1 1 calc(50% - 8px)" } },
      {
        id: "period_date",
        label: "조회 기간 (날짜)",
        type: "date-range",
        required: true,
        flexStyle: { flex: "1 1 100%" },
      },
      {
        id: "period_datetime",
        label: "조회 기간 (시간)",
        type: "date-range",
        granularity: "datetime",
        required: true,
        flexStyle: { flex: "1 1 100%" },
      },
      {
        id: "period_month",
        label: "조회 기간 (월)",
        type: "date-range",
        granularity: "month",
        required: true,
        flexStyle: { flex: "1 1 100%" },
      },
      {
        id: "period_year",
        label: "조회 기간 (연도)",
        type: "date-range",
        granularity: "year",
        required: true, flexStyle: { flex: "1 1 100%" },
      },
      {
        id: "status_radio",
        label: "라디오그룹",
        type: "radio-group",
        value: "0",
        required: true,
        flexStyle: { flex: "1 1 calc(50% - 8px)"},
        options: [
          { value: "1", label: "사용" },
          { value: "0", label: "미사용" },
        ],
      },
      {
        id: "options_check",
        label: "체크박스그룹",
        type: "checkbox-group",
        value: ["weekly", "yearly"],
        required: true,
        flexStyle: { flex: "1 1 calc(50% - 8px)" },
        options: [
          { value: "daily", label: "일간", disabled: true },
          { value: "weekly", label: "주간" },
          { value: "monthly", label: "월간" },
          { value: "yearly", label: "년간" },
        ],
      },
      {
        id: "measurement",
        label: "인풋그룹",
        type: "input-group",
        required: true,
        flexStyle: { flex: "1 1 100%" },
        items: [
          {
            type: "input",
            inputType: "number",
            id: "value",
            name: "value",
            required: true,
            placeholder: "값 입력",
            style: "flex: 1;",
          },
          {
            type: "select",
            id: "unit",
            name: "unit",
            required: true,
            value: "mm",
            style: "flex: 1;",
            options: [
              { value: "mm", text: "mm" },
              { value: "cm", text: "cm" },
              { value: "m", text: "m" },
              { value: "inch", text: "inch" },
            ],
          },
        ],
      },
      {
        id: "ip",
        label: "IP 주소",
        type: "input-group",
        required: true,
        flexStyle: { flex: "1 1 100%" },
        items: [
          {
            type: "input",
            inputType: "number",
            id: "part1",
            name: "part1",
            min: 0,
            max: 255,
            required: true,
            placeholder: "000",
            style: "width: 1em; text-align: center;",
          },
          { type: "separator", text: "." },
          {
            type: "input",
            inputType: "number",
            id: "part2",
            name: "part2",
            min: 0,
            max: 255,
            required: true,
            placeholder: "000",
            style: "width: 1em; text-align: center;",
          },
          { type: "separator", text: "." },
          {
            type: "input",
            inputType: "number",
            id: "part3",
            name: "part3",
            min: 0,
            max: 255,
            required: true,
            placeholder: "000",
            style: "width: 1em; text-align: center;",
          },
          { type: "separator", text: "." },
          {
            type: "input",
            inputType: "number",
            id: "part4",
            name: "part4",
            min: 0,
            max: 255,
            required: true,
            placeholder: "000",
            style: "width: 1em; text-align: center;",
          },
        ],
      },
      {
        id: "attachments",
        label: "첨부 파일",
        type: "table",
        editable: true,
        required: false,
        flexStyle: { flex: "1 1 100%" },
        allowFileUpload: true,
        tableHeaderActions: [
          { text: "파일 추가", class: "primary small", action: "add-file" }
        ],
        columns: [
          { key: 'name', header: '파일명', type: 'link', linkHrefKey: 'url', width: '50%', placeholder: '링크 없음' },
          { key: 'size', header: '크기', type: 'text', align: 'right', width: '20%', format: 'fileSize' },
          {
            key: 'actions', header: '관리', type: 'button', align: 'center', width: '30%',
            buttonText: '삭제', buttonAction: 'remove-row',
            buttonClass: 'button--ghost button--text button--xsmall',
          }
        ],
      },
      {
        id: "history",
        type: "table", 
        label: "공통테이블",
        flexStyle: { flex: "1 1 100%" },
        editable: true, 
        tableHeaderActions: [ 
          { text: "전체행제거", class: "secondary small", action: "remove-all-rows" }, 
          { text: "추가", class: "primary small", action: "add-row-common" },
        ],
        columns: [
          { key: 'date', header: '변경일시', type: 'text', width: '30%' },
          { key: 'user', header: '변경자', type: 'text', width: '20%' },
          { key: 'content', header: '변경내용', type: 'text', width: '30%' },
          {
            key: 'details', header: '상세', type: 'button', align: 'center', width: '20%',
            buttonAction: 'viewHistoryDetail', buttonClass: 'button--text button--xsmall',
            buttonText: '상세보기',
          },
          {
            key: 'delete', header: '삭제', type: 'button', align: 'center', width: '20%',
            buttonIcon: 'remove', buttonAction: 'remove-row',
            buttonClass: 'button--ghost button--icon button--xsmall',
          }
        ],
      },
      {
        id: "readonly_files",
        label: "첨부파일",
        type: "table", 
        flexStyle: { flex: "1 1 100%" },
        allowFileUpload: true,
        columns: [
          { key: 'name', header: '파일명', type: 'link', linkHrefKey: 'url', width: '70%' },
          { key: 'size', header: '크기', type: 'text', align: 'right', width: '30%' },
        ],
      },
      {
        id: "terms_agree",
        label: "개인정보 수집 및 이용 동의",
        type: "checkbox",
        checked: true,
        flexStyle: { flex: "1 1 100%" },
        required: false,
      },
      {
        id: "board",
        type: "table",
        flexStyle: { flex: "1 1 100%" },
        columns: [
          { key: 'no', header: 'No.', type: 'text',  width: '10%', placeholder: 'serial', align: 'right' },
          { key: 'title', header: '제목', type: 'text',  width: '30%', placeholder: 'serial', align: 'left' },
          { key: 'author', header: '작성자', type: 'text',  width: '30%', placeholder: 'serial', align: 'center' },
          { key: 'createdAt', header: '게시일', type: 'text',  width: '30%', placeholder: 'serial', align: 'center' },
        ],
        rows: [
          { no: '1', title: '게시판 그리드용으로 만든', author: '김코코', createdAt: '2023-10-26' },
          { no: '2', title: '라벨과 액션없는 테이블', author: '박모코', createdAt: '2023-10-27' },
          { no: '3', title: 'TODO: 테이블 필터상단에 추가', author: '이명박', createdAt: '2023-10-28' },
          { no: '4', title: 'TODO: 페이지네이션 하단에 추가', author: '박근혜', createdAt: '2023-10-29' },
        ]
      },
      {
        id: "thumbnail",
        label: "리포트 썸네일",
        type: "image-upload",
        headerActions: [
          { 
            text: '삭제',
            class: 'secondary small', 
            action: 'remove-image',
            id: 'thumbnail-remove-btn',
            'data-target-input': 'thumbnail',
            style: 'display: none;'
          },
          { 
            text: '파일 선택',
            class: 'primary small', 
            action: 'select-image',
            'data-target-input': 'thumbnail'
          }
        ],
        accept: "image/png, image/jpeg, image/gif",
        maxSizeMB: 2,
        preview: true,
        required: false,
        flexStyle: { flex: "1 1 100%" },
        placeholder: "썸네일을 업로드하세요",
      },
    ],
    footerActions: [
      { text: "취소", class: "secondary", size: "medium", action: "cancel" },
      { text: "등록", class: "primary", type: "submit", size: "medium", action: "submit" },
    ],
  },
  bizMetaDetail: {
    dialogWidth: "960px",
    dialogLayout: "2-column-grid",
    type: "modal",
    title: "예시)혁신기업 발굴 및 창업수출 지원 캠페인",
    fields: [
      {
        id: "thumbnail",
        label: "리포트 썸네일",
        headerActions: [
          { 
            text: '삭제',
            class: 'secondary small', 
            action: 'remove-image',
            id: 'thumbnail-remove-btn',
            'data-target-input': 'thumbnail',
            style: 'display: none;'
          },
          { 
            text: '파일 선택',
            class: 'primary small', 
            action: 'select-image',
            'data-target-input': 'thumbnail'
          }
          
        ],
        type: "image-upload",
        accept: "image/png, image/jpeg, image/gif",
        maxSizeMB: 2,
        preview: true,
        required: false,
        flexStyle: { flex: "1 1 100%" },
        colSpan: 2,
      },
      {
        id: "title",
        label: "리포트 제목",
        type: "text",
        required: true,
        colSpan: 1,
        placeholder: "",
      },
      {
        id: "date",
        label: "작성일",
        type: "text",
        required: true,
        readonly: true,
        colSpan: 1,
      },
      {
        id: "category",
        label: "분류",
        type: "text",
        required: true,
        colSpan: 1,
        placeholder: "",
      },
      {
        id: "authorization",
        label: "권한",
        type: "text",
        required: true,
        colSpan: 1,
        placeholder: "",
      },
      {
        id: "path",
        label: "리포트 경로",
        type: "text",
        required: true,
        colSpan: 1,
        placeholder: "",
      },
      {
        id: "owner",
        label: "소유자",
        type: "text",
        required: true,
        colSpan: 1,
        placeholder: "",
      },
      {
        id: "description",
        label: "리포트 설명",
        type: "textarea",
        required: true,
        colSpan: 1,
        placeholder: "",
      },
    ],
    footerActions: [
      { text: "취소", class: "secondary", size: "medium", action: "close" },
      { text: "등록", class: "primary", size: "medium", action: "submit" },
    ],
  },
  
};

export default templates;
